/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsOrganizationRouteImport } from './routes/settings.organization'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ChatPackPackIdRouteImport } from './routes/_chat.pack.$packId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatAnalyticsProjectIdRouteImport } from './routes/_chat.analytics.$projectId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as ChatProjectEnvironmentIdProjectIdRouteImport } from './routes/_chat.project.$environmentId.$projectId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatPackPackIdRoute = ChatPackPackIdRouteImport.update({
  id: '/pack/$packId',
  path: '/pack/$packId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAnalyticsProjectIdRoute = ChatAnalyticsProjectIdRouteImport.update({
  id: '/analytics/$projectId',
  path: '/analytics/$projectId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatProjectEnvironmentIdProjectIdRoute =
  ChatProjectEnvironmentIdProjectIdRouteImport.update({
    id: '/project/$environmentId/$projectId',
    path: '/project/$environmentId/$projectId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/invite': typeof InviteRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/analytics/$projectId': typeof ChatAnalyticsProjectIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/pack/$packId': typeof ChatPackPackIdRoute
  '/project/$environmentId/$projectId': typeof ChatProjectEnvironmentIdProjectIdRoute
}
export interface FileRoutesByTo {
  '/invite': typeof InviteRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/analytics/$projectId': typeof ChatAnalyticsProjectIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/pack/$packId': typeof ChatPackPackIdRoute
  '/project/$environmentId/$projectId': typeof ChatProjectEnvironmentIdProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/invite': typeof InviteRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/analytics/$projectId': typeof ChatAnalyticsProjectIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_chat/pack/$packId': typeof ChatPackPackIdRoute
  '/_chat/project/$environmentId/$projectId': typeof ChatProjectEnvironmentIdProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/pair'
    | '/settings'
    | '/settings/account'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/organization'
    | '/$environmentId/$threadId'
    | '/analytics/$projectId'
    | '/draft/$draftId'
    | '/pack/$packId'
    | '/project/$environmentId/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/pair'
    | '/settings'
    | '/settings/account'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/organization'
    | '/'
    | '/$environmentId/$threadId'
    | '/analytics/$projectId'
    | '/draft/$draftId'
    | '/pack/$packId'
    | '/project/$environmentId/$projectId'
  id:
    | '__root__'
    | '/_chat'
    | '/invite'
    | '/pair'
    | '/settings'
    | '/settings/account'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/organization'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/analytics/$projectId'
    | '/_chat/draft/$draftId'
    | '/_chat/pack/$packId'
    | '/_chat/project/$environmentId/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  InviteRoute: typeof InviteRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/pack/$packId': {
      id: '/_chat/pack/$packId'
      path: '/pack/$packId'
      fullPath: '/pack/$packId'
      preLoaderRoute: typeof ChatPackPackIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/analytics/$projectId': {
      id: '/_chat/analytics/$projectId'
      path: '/analytics/$projectId'
      fullPath: '/analytics/$projectId'
      preLoaderRoute: typeof ChatAnalyticsProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/project/$environmentId/$projectId': {
      id: '/_chat/project/$environmentId/$projectId'
      path: '/project/$environmentId/$projectId'
      fullPath: '/project/$environmentId/$projectId'
      preLoaderRoute: typeof ChatProjectEnvironmentIdProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatAnalyticsProjectIdRoute: typeof ChatAnalyticsProjectIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
  ChatPackPackIdRoute: typeof ChatPackPackIdRoute
  ChatProjectEnvironmentIdProjectIdRoute: typeof ChatProjectEnvironmentIdProjectIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatAnalyticsProjectIdRoute: ChatAnalyticsProjectIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
  ChatPackPackIdRoute: ChatPackPackIdRoute,
  ChatProjectEnvironmentIdProjectIdRoute:
    ChatProjectEnvironmentIdProjectIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  InviteRoute: InviteRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
