import { describe, expect, it } from "vitest";

import { curateCodexConfigToml } from "./curatedCodexHome.ts";

const SOURCE = `model = "gpt-5.6-terra"
model_reasoning_effort = "high"

service_tier = "default"

notify = ["/Users/hico/.codex/computer-use/SkyComputerUseClient", "turn-ended"]

[projects."/Users/hico/Desktop/waleed_codes/p36/t3code"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
"gpt-5.4" = "gpt-5.6-terra"

[mcp_servers.chrome-devtools]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest"]

[mcp_servers.chrome-devtools.tools.take_snapshot]
enabled = true

[mcp_servers.node_repl]
command = "node"

[mcp_servers.node_repl.env]
NODE_ENV = "development"

[plugins."sites@openai-bundled"]
enabled = true

[plugins."github@openai-curated"]
enabled = true
`;

describe("curateCodexConfigToml", () => {
  const curated = curateCodexConfigToml(SOURCE);

  it("drops every MCP server table, including nested ones", () => {
    expect(curated).not.toContain("mcp_servers");
    expect(curated).not.toContain("chrome-devtools");
    expect(curated).not.toContain("node_repl");
    // The nested tables must go with their parent, not survive as orphans.
    expect(curated).not.toContain("take_snapshot");
    expect(curated).not.toContain("NODE_ENV");
  });

  it("drops every provider plugin, which is how an untracked deploy happened", () => {
    expect(curated).not.toContain("[plugins");
    expect(curated).not.toContain("sites@openai-bundled");
    expect(curated).not.toContain("github@openai-curated");
  });

  it("drops the rest of the tool surface, not just the obvious two", () => {
    const curated = curateCodexConfigToml(
      [
        '[apps.connector_abc.tools.gmail_send_email]',
        'approval_mode = "approve"',
        "",
        "[marketplaces.openai-bundled]",
        'source_type = "local"',
        "",
        "[[skills.config]]",
        'path = "/Users/hico/.codex/plugins/cache/openai-bundled/browser/SKILL.md"',
        "",
        "[shell_environment_policy.set]",
        'NODE_REPL_TRUSTED_CODE_PATHS = "/Users/hico/.codex"',
        "",
        "[tui.model_availability_nux]",
        '"gpt-5.5" = 4',
      ].join("\n"),
    );

    // A connector tool is a tool the agent can call and T3 cannot see, which is
    // the same problem as a plugin.
    expect(curated).not.toContain("gmail_send_email");
    expect(curated).not.toContain("[marketplaces");
    expect(curated).not.toContain("skills.config");
    expect(curated).not.toContain("NODE_REPL_TRUSTED_CODE_PATHS");
    // Terminal-UI preferences are not a tool surface and are left alone.
    expect(curated).toContain("[tui.model_availability_nux]");
  });

  it("keeps the model and its reasoning settings", () => {
    expect(curated).toContain('model = "gpt-5.6-terra"');
    expect(curated).toContain('model_reasoning_effort = "high"');
    expect(curated).toContain('service_tier = "default"');
  });

  it("keeps the migration table, because it decides which model actually runs", () => {
    // Asking for gpt-5.3-codex resolves through this chain to gpt-5.6-terra.
    // Dropping it would quietly change the model without changing the request.
    expect(curated).toContain("[notice.model_migrations]");
    expect(curated).toContain('"gpt-5.3-codex" = "gpt-5.4"');
    expect(curated).toContain('"gpt-5.4" = "gpt-5.6-terra"');
  });

  it("keeps per-folder trust, so a workspace is not re-prompted", () => {
    expect(curated).toContain('[projects."/Users/hico/Desktop/waleed_codes/p36/t3code"]');
    expect(curated).toContain('trust_level = "trusted"');
  });

  it("drops the desktop notify hook", () => {
    expect(curated).not.toContain("notify");
    expect(curated).not.toContain("SkyComputerUseClient");
  });

  it("says the file is generated, so nobody edits it expecting it to survive", () => {
    expect(curated.startsWith("# Generated by T3 Code.")).toBe(true);
  });

  it("drops a multi-line dropped value whole, leaving no stray syntax", () => {
    const multiline = curateCodexConfigToml(
      ['model = "gpt-5.6-terra"', "notify = [", '  "one",', '  "two",', "]", 'x = "kept"'].join(
        "\n",
      ),
    );
    expect(multiline).not.toContain("notify");
    expect(multiline).not.toContain('"one"');
    expect(multiline).not.toContain("]");
    expect(multiline).toContain('x = "kept"');
  });

  it("leaves a table it does not recognise exactly as written", () => {
    const unknown = curateCodexConfigToml('[some_future_table]\nkey = "value"\n');
    expect(unknown).toContain("[some_future_table]");
    expect(unknown).toContain('key = "value"');
  });

  it("survives a config with nothing in it", () => {
    expect(() => curateCodexConfigToml("")).not.toThrow();
  });
});
