import { homedir } from "node:os";

import { Effect, FileSystem, Path } from "effect";

/**
 * Table prefixes that describe tools rather than the model.
 *
 * These are the whole reason a curated home exists. `~/.codex/config.toml`
 * belongs to the person, not to T3, and everything they have configured for
 * their own CLI is inherited by every agent T3 spawns — including the plugins
 * that can publish a site. An agent that deploys through one of those leaves T3
 * with no deployment record, no ingest key and nothing on the infrastructure or
 * analytics pages.
 */
const DROPPED_TABLE_PREFIXES = [
  "mcp_servers",
  "plugins",
  // Connector tools, e.g. `[apps.connector_….tools.gmail_send_email]`. Same
  // thing as a plugin from the agent's side: a tool it can call that T3 knows
  // nothing about.
  "apps",
  // Where the plugins above are installed from. Inert once they are gone, but
  // it is plugin machinery and does not belong in a home that has none.
  "marketplaces",
  // Skills are loaded out of `plugins/cache/…`, so they arrive with the
  // plugins and leave with them.
  "skills",
  // Exists to support the dropped servers — it whitelists code paths and
  // browser backends for node_repl and the in-app browser.
  "shell_environment_policy",
] as const;

/**
 * Top-level keys dropped from the preamble. `notify` runs a program of the
 * user's choosing when a turn ends; that is a personal desktop integration and
 * not something a server-spawned agent should be firing.
 */
const DROPPED_PREAMBLE_KEYS = ["notify"] as const;

const GENERATED_HEADER = `# Generated by T3 Code. Do not edit — rewritten whenever a Codex session starts.
#
# This is a curated copy of the user's own Codex config. The model, its
# reasoning settings, the model-migration table and the per-folder trust levels
# are carried over so an agent runs the same model against the same trusted
# folders it always has. MCP servers and provider plugins are deliberately left
# out, so a deploy goes through a pack or the project's deploy path — somewhere
# T3 can record it — rather than through a tool it cannot see.
`;

/** The `[name]` or `[[name]]` a line opens, or null when it opens no table. */
function tableHeaderName(line: string): string | null {
  const trimmed = line.trim();
  if (!trimmed.startsWith("[") || !trimmed.endsWith("]")) {
    return null;
  }
  const inner =
    trimmed.startsWith("[[") && trimmed.endsWith("]]")
      ? trimmed.slice(2, -2)
      : trimmed.slice(1, -1);
  return inner.trim();
}

function isDroppedTable(headerName: string): boolean {
  return DROPPED_TABLE_PREFIXES.some(
    (prefix) => headerName === prefix || headerName.startsWith(`${prefix}.`),
  );
}

/** The bare key a `key = value` line assigns, or null. Quoted keys included. */
function assignedKey(line: string): string | null {
  const match = /^\s*([A-Za-z0-9_.-]+|"[^"]*")\s*=/.exec(line);
  return match?.[1] ?? null;
}

/**
 * How many brackets a line leaves open, so a multi-line array value is dropped
 * whole rather than leaving its tail behind as stray syntax. Brackets inside
 * strings would throw this off; none of the keys being dropped carry any.
 */
function bracketDelta(line: string): number {
  let delta = 0;
  for (const character of line) {
    if (character === "[") delta += 1;
    else if (character === "]") delta -= 1;
  }
  return delta;
}

/**
 * Strip the tool tables out of a Codex `config.toml`, keeping everything that
 * decides which model runs and which folders are trusted.
 *
 * Deliberately a line filter rather than a parse-and-re-serialize: round-
 * tripping through a TOML writer would reformat and reorder a file the user
 * still owns, and any key this code does not model would be silently dropped.
 * Keeping the original lines means anything not explicitly removed survives
 * exactly as written.
 */
export function curateCodexConfigToml(source: string): string {
  const lines = source.split("\n");
  const kept: string[] = [];
  let droppingTable = false;
  let droppingKeyDepth = 0;

  for (const line of lines) {
    if (droppingKeyDepth > 0) {
      droppingKeyDepth += bracketDelta(line);
      continue;
    }

    const headerName = tableHeaderName(line);
    if (headerName !== null) {
      droppingTable = isDroppedTable(headerName);
      if (droppingTable) {
        continue;
      }
      kept.push(line);
      continue;
    }

    if (droppingTable) {
      continue;
    }

    const key = assignedKey(line);
    if (
      key !== null &&
      DROPPED_PREAMBLE_KEYS.includes(key as (typeof DROPPED_PREAMBLE_KEYS)[number])
    ) {
      droppingKeyDepth = bracketDelta(line);
      continue;
    }

    kept.push(line);
  }

  // Collapse the runs of blank lines a removed table leaves behind, so the file
  // does not grow a hole where every plugin used to be.
  const body: string[] = [];
  for (const line of kept) {
    if (line.trim().length === 0 && body.at(-1)?.trim().length === 0) {
      continue;
    }
    body.push(line);
  }

  return `${GENERATED_HEADER}\n${body.join("\n").trim()}\n`;
}

export interface CuratedCodexHome {
  readonly path: string;
  /** False when the user's own home had nothing to curate from. */
  readonly curatedFromSource: boolean;
}

/**
 * Materialize the home T3 launches Codex with.
 *
 * The credentials are linked rather than copied, so logging in or out of Codex
 * in a terminal is immediately true for T3 as well and there is never a second
 * stale copy of a token on disk. Everything else is regenerated on each call,
 * which is what keeps a newly trusted folder or a changed model from going
 * stale here.
 *
 * Nothing in the user's own home is written to. The isolation is one
 * directional: `codex` in a terminal is untouched.
 */
export const ensureCuratedCodexHome = Effect.fn("ensureCuratedCodexHome")(function* (input: {
  readonly sourceHome: string;
  readonly targetHome: string;
}) {
  const fileSystem = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  yield* fileSystem.makeDirectory(input.targetHome, { recursive: true });

  const sourceConfigPath = path.join(input.sourceHome, "config.toml");
  const sourceConfig = yield* fileSystem
    .readFileString(sourceConfigPath)
    .pipe(Effect.catch(() => Effect.succeed(null)));

  yield* fileSystem.writeFileString(
    path.join(input.targetHome, "config.toml"),
    sourceConfig === null ? GENERATED_HEADER : curateCodexConfigToml(sourceConfig),
  );

  // A dangling link is worse than no link: Codex would read it as a corrupt
  // auth file rather than as "not signed in".
  const sourceAuthPath = path.join(input.sourceHome, "auth.json");
  const targetAuthPath = path.join(input.targetHome, "auth.json");
  const sourceAuthExists = yield* fileSystem
    .exists(sourceAuthPath)
    .pipe(Effect.catch(() => Effect.succeed(false)));

  yield* fileSystem.remove(targetAuthPath).pipe(Effect.catch(() => Effect.void));
  if (sourceAuthExists) {
    yield* fileSystem.symlink(sourceAuthPath, targetAuthPath).pipe(Effect.catch(() => Effect.void));
  }

  return {
    path: input.targetHome,
    curatedFromSource: sourceConfig !== null,
  } satisfies CuratedCodexHome;
});

/**
 * One home for the whole install, under the server's own state directory.
 *
 * Shared rather than per-workspace on purpose: this is how `~/.codex` already
 * behaves, one login covers every project, and per-folder trust is a table
 * inside the config rather than a reason to keep several homes.
 */
export const CURATED_CODEX_HOME_SEGMENTS = ["provider-homes", "codex"] as const;

/** Where Codex would have read from if T3 did nothing. */
function personalCodexHome(join: (...segments: string[]) => string): string {
  const configured = process.env["CODEX_HOME"];
  return configured !== undefined && configured.trim().length > 0
    ? configured.trim()
    : join(homedir(), ".codex");
}

export const resolveCuratedCodexHome = Effect.fn("resolveCuratedCodexHome")(function* (input: {
  readonly stateDir: string;
}) {
  const path = yield* Path.Path;
  return yield* ensureCuratedCodexHome({
    sourceHome: personalCodexHome((...segments) => path.join(...segments)),
    targetHome: path.join(input.stateDir, ...CURATED_CODEX_HOME_SEGMENTS),
  });
});
