export {
  getPrimaryKnownEnvironment,
  readPrimaryEnvironmentDescriptor,
  resetPrimaryEnvironmentDescriptorForTests,
  resolveInitialPrimaryEnvironmentDescriptor,
  usePrimaryEnvironmentId,
  writePrimaryEnvironmentDescriptor,
  __resetPrimaryEnvironmentBootstrapForTests,
  __resetPrimaryEnvironmentDescriptorBootstrapForTests,
} from "./context";

export {
  resolveInitialPrimaryEnvironmentDescriptor as ensurePrimaryEnvironmentReady,
  writePrimaryEnvironmentDescriptor as updatePrimaryEnvironmentDescriptor,
} from "./context";

export {
  createBrowserHandoffCredential,
  createServerPairingCredential,
  fetchOnboardingState,
  fetchSessionState,
  fetchSupabaseBearerSessionState,
  fetchSupabaseBearerUserProfile,
  fetchSupabasePublicAuthConfig,
  fetchUserPreferences,
  fetchUserProfile,
  issueSupabaseBearerWebSocketToken,
  listServerClientSessions,
  listServerPairingLinks,
  peekPairingTokenFromUrl,
  submitOnboarding,
  updateUserPreferences,
  readSupabasePublicAuthConfig,
  readSupabaseBrowserAccessToken,
  readSupabaseBrowserRefreshToken,
  removeSupabaseBrowserAccessToken,
  resolveInitialServerAuthGateState,
  resolveSupabasePrimaryWebSocketConnectionUrl,
  revokeOtherServerClientSessions,
  revokeServerClientSession,
  revokeServerPairingLink,
  signOutLocalServerSession,
  signOutSupabaseBrowserSession,
  subscribeSupabaseBrowserSessionChanges,
  submitSupabaseBrowserAccessToken,
  submitLocalPasswordAuth,
  submitSupabasePasswordAuth,
  stripPairingTokenFromUrl,
  submitServerAuthCredential,
  takePairingTokenFromUrl,
  updateUserProfile,
  writeSupabaseBrowserAccessToken,
  type ServerClientSessionRecord,
  type ServerAuthGateState,
  type ServerPairingLinkRecord,
  type SupabasePasswordAuthMode,
  __resetServerAuthBootstrapForTests,
} from "./auth";
export {
  fetchGatewayApiKey,
  fetchGatewayUsage,
  redeemGatewayCode,
  type GatewayRedeemResult,
  type GatewayUsageResult,
  type GatewaySessionWindow,
  type GatewayUsageBySource,
  type GatewayDailyActivity,
} from "./gateway";
export {
  fetchIntegrationsStatus,
  startIntegrationAuthorize,
  disconnectIntegration,
  type IntegrationProvider,
  type IntegrationConnectionStatus,
  type IntegrationsStatus,
} from "./integrations";

export { resolvePrimaryEnvironmentHttpUrl, isLoopbackHostname } from "./target";
