export {
  getPrimaryKnownEnvironment,
  readPrimaryEnvironmentDescriptor,
  resetPrimaryEnvironmentDescriptorForTests,
  resolveInitialPrimaryEnvironmentDescriptor,
  usePrimaryEnvironmentId,
  writePrimaryEnvironmentDescriptor,
  __resetPrimaryEnvironmentBootstrapForTests,
  __resetPrimaryEnvironmentDescriptorBootstrapForTests,
} from "./context";

export {
  resolveInitialPrimaryEnvironmentDescriptor as ensurePrimaryEnvironmentReady,
  writePrimaryEnvironmentDescriptor as updatePrimaryEnvironmentDescriptor,
} from "./context";

export {
  createBrowserHandoffCredential,
  createServerPairingCredential,
  fetchOnboardingState,
  fetchSessionState,
  fetchSupabaseBearerSessionState,
  fetchSupabaseBearerUserProfile,
  fetchSupabasePublicAuthConfig,
  fetchUserProfile,
  issueSupabaseBearerWebSocketToken,
  listServerClientSessions,
  listServerPairingLinks,
  peekPairingTokenFromUrl,
  readSupabasePublicAuthConfig,
  readSupabaseBrowserAccessToken,
  readSupabaseBrowserRefreshToken,
  removeSupabaseBrowserAccessToken,
  resolveInitialServerAuthGateState,
  resolveSupabasePrimaryWebSocketConnectionUrl,
  revokeOtherServerClientSessions,
  revokeServerClientSession,
  revokeServerPairingLink,
  signOutLocalServerSession,
  signOutSupabaseBrowserSession,
  subscribeSupabaseBrowserSessionChanges,
  submitSupabaseBrowserAccessToken,
  submitLocalPasswordAuth,
  submitSupabasePasswordAuth,
  stripPairingTokenFromUrl,
  submitServerAuthCredential,
  takePairingTokenFromUrl,
  updateUserProfile,
  writeSupabaseBrowserAccessToken,
  type ServerClientSessionRecord,
  type ServerAuthGateState,
  type ServerPairingLinkRecord,
  type SupabasePasswordAuthMode,
  __resetServerAuthBootstrapForTests,
} from "./auth";

export { resolvePrimaryEnvironmentHttpUrl, isLoopbackHostname } from "./target";
